catch (${1:err}) {
	${2}
}
